#! /bin/csh -f
# t2prob_script
# 03.16.94 by Jose' Ma. Maisog, M.D.
# Laboratory of Psychology and Psychopathology,
# National Institute of Mental Health

# Shell script to convert t-test images to probability images

# C executables called: get_dims_from, t2prob, makeheader4

# QUERY USER FOR IMAGE DIRECTORY
touch fidap.log
scroll 10
echo  ""
echo '******************************************************'
echo  ""
echo This script will convert floating point t-test images to floating point
echo probability images.  The t-test images must be floating point ANALYZE 
echo images and must have appropriate ANALYZE headers.  You must have read/write
echo access to the directory in which the images are kept.
echo ""
echo -n "Please enter directory in which floating point t-test images are kept: "
set dir = $<
while (! -e $dir)
    echo Directory $dir does not exist.
    echo ""
    echo -n "Please enter directory in which floating point t-test images are kept: "
    set dir = $<
end
cd $dir
echo '******************************************************' >> fidap. log
echo `date` " : " $user " : " t2prob_script >> fidap.log

# MAKE LIST OF IMAGES TO BE REGISTERED
echo  ""
echo '******************************************************'
echo  ""
echo Here are the ANALYZE images found in this directory:
ls *.img
echo ""
echo Need root name of images to be converted.  This is the left-most
echo string of characters in the image filenames which will match all
echo of the images you wish to slice, and ONLY those images.
echo ""
echo -n "Type in root name of images to be converted: "
set rootname = $<
echo ""
set list = $rootname*.img
echo These t-test images are going to be converted to probability images:
echo $list
echo ""
echo They are assumed to already have ANALYZE headers.

# GET DEGREES OF FREEDOM FOR EACH t-TEST IMAGE
echo  ""
echo '******************************************************'
echo  ""
echo You will now have to type in the degrees of freedom for each
echo t-test image.  Degrees of freedom may need to be corrected
echo for spatial and/or temporal autocorrelations.
echo ""
set df
set img_no = 1
while ($img_no <= $#list)
    echo -n "Degrees of freedom for $list[$img_no]? "
    set df = ($df $<)
    echo df for $list[$img_no] is $df >> fidap.log
    echo ""
    @ img_no++
end

# INFORMATION ABOUT OUTPUT IMAGE FILES
echo  ""
echo '******************************************************'
echo  ""
echo t-test images will be converted to floating point probability images with
echo naming convention
echo ""
echo "    P<filename>"
echo ""
echo where <filename> is the name of the original t-test image.
echo ""

# CHECK WITH USER IF IT'S OKAY TO GO ON
echo ""
echo ""
echo -n "Continue <y/n>? "
set choice = $<
if ($choice != "y") then
    echo QUITTING SHELL SCRIPT....
    sleep 2
    exit
endif

# LOOP OVER ALL T-TEST IMAGES
set img_no = 1
while ($img_no <= $#list)
    echo ""
    echo Converting $list[$img_no] to P$list[$img_no]...

    # CALL t2prob
    t2prob $list[$img_no] $df[$img_no] P$list[$img_no]

    # MAKE HEADER FOR PROBABILITY IMAGE
    set dims = `get_dims_from $list[$img_no]:r.hdr`
    makeheader4 P$list[$img_no]:r.hdr $dims 1 32 1000 0 1000 0 16

    @ img_no++
end

