#include <math.h>
#include <stdio.h>
#include <stdlib.h>
float *float_malloc(int num_vox);
int read_float_data(char *filename, float *array, int num_items);
int float_fwrite(char *filename, float *array, int num_items);

main(int argc, char *argv[])
{
    /* 10.28.96 : JM Maisog
        General program for converting an F-test map to a Z-score map.
        Note that the method of conversion depends on the numerator df.

        If the number of degrees of freedom in the numerator is 1, the square
        root of the F-test is taken, converting it to an unsigned t-test.
        The sign of the t-test is then determined from a separate map,
        e.g., the B_hat regression coefficient map generated by multiple
        regression, if this is given.  Then, the method of Federighi is used
        to convert the t-test to an approximate Z-score.  In the resulting
        Z-score map, large negative Z-scores will represent significant
        "deactivations."  Large positive Z-scores will be significant
        "activations."

        If the number of degrees of freedom is not 1, then the method of
        Paulson is used to convert the F-test to an approximate Z-score.
        In the resulting Z-score map, low values of the F-test near zero will
        map onto large negative Z-scores, which will therefore represent
        NON-significant voxels.  Only large positive Z-scores will be
        significant.

        References:

        Federighi, E.T., "Extended tables of the percentage points of
        Student's t-distribution," J. Am. Stat. Assoc., 54, 683-688 (1959).
        
        Paulson E, "An approximate normalization of the Analysis of Variance
        distribution," Ann Math Statist 13:233-235 (1942).                      */

    FILE *fIN;                /* Pointer to input image file.                   */
    FILE *fOUT;               /* Pointer to output image file.                  */
    float *stats_map;         /* F-test                                         */
    int v1, v2;               /* Numerator and denominator degrees of freedom.  */
    float scalefactor;        /* Factor by which F will be scaled.              */
    float *sign_map;          /* Map to determine signs.  If a voxel in this    */
                              /* map is negative, the corresponding voxel in    */
                              /* the Z-score map will be given a negative sign. */
    float *Z_score_map;       /* Pointer to output probability image.           */
    int num_voxX4;            /* Number of bytes in image.                      */
    int num_vox;              /* Number of voxels in image.                     */
    int vox_index;            /* Index into voxels in image.                    */


/* ---------------------------------------------------------------------------- */
/*  CHECK TO SEE IF CORRECT NUMBER OF ARGUMENTS WERE PASSED.                    */

    if ((argc!=6) && (argc!=7)) {
        printf("F2Z: need input F-test map, numerator degrees of freedom,\n");
        printf("     denominator degrees of freedom, scalefactor,\n");
        printf("     and output file name.\n\n");

        printf("You can include an optional sixth argument, which is a map from\n");
        printf("which signs are to be determined, if the numerator df is 1.\n\n");

        printf("This program will convert an F-test map to a Z-score map.\n");
        printf("First, the F-test is multiplied the scalefactor; this is done if\n");
        printf("you wish to adjust for correlated observations.  If you don't want\n");
        printf("such an adjustment, use a scalefactor of 1.  Then, the F-test is\n");
        printf("converted to a Z-score using one of two approximate methods.\n\n");

        printf("If the numerator degrees of freedom is not 1, the method of\n");
        printf("Paulson will be used.  In the resulting Z-score map, low values\n");
        printf("of the F-test near zero will map onto large negative Z-scores,\n");
        printf("which will therefore represent NON-significant voxels.  Only large\n");
        printf("positive Z-scores will be significant.\n\n");

        printf("If the numerator degrees of freedom is exactly 1, the square root\n");
        printf("of the F-tests will be taken, generating in memory a map of unsigned\n");
        printf("t-tests.  Then, the method of Federighi is used to convert the\n");
        printf("unsigned t-tests to approximate unsigned Z-scores.  Finally, if given,\n");
        printf("the floating point map from which to determine signs is then evaluated,\n");
        printf("voxel-by-voxel; if a negative value is found, the corresponding voxel\n");
        printf("in the Z-score map is multiplied by -1. If you're converting an F-test\n");
        printf("map from the multiple regression analysis, you should use the B_hat\n");
        printf("regression coefficient map as the map from which to determine signs. \n\n");

        printf("References:\n\n");

        printf("Federighi, E.T., \"Extended tables of the percentage points of\n");
        printf("Student's t-distribution,\" J. Am. Stat. Assoc., 54, 683-688 (1959).\n\n");

        printf("Paulson E, \"An approximate normalization of the Analysis of Variance\n");
        printf("distribution,\" Ann Math Statist 13:233-235 (1942).\n");

        exit(1);
    }


/* ---------------------------------------------------------------------------- */
/*  READ IN COMMAND LINE ARGUMENTS.                                             */

    v1          = atoi(argv[2]);
    v2          = atoi(argv[3]);
    scalefactor = atof(argv[4]);


/* ---------------------------------------------------------------------------- */
/* COUNT NUMBER OF VOXELS IN F_TEST MAP.                                        */

    num_voxX4 = 0;
    if ((fIN=fopen(argv[1],"r")) == NULL) {
        printf("F2Z: can't open %s\n",argv[1]);
        exit(2);
    }
    while (fgetc(fIN)!=EOF)
        num_voxX4++;
    fclose(fIN);

    num_vox = num_voxX4/4;
/*    printf("F2Z: number of voxels = %d\n",num_vox); */

/* ---------------------------------------------------------------------------- */
/* ASSIGN MEMORY.                                                               */

    stats_map = float_malloc(num_vox);
    Z_score_map = float_malloc(num_vox);

/* ---------------------------------------------------------------------------- */
/* READ IN FLOATING POINT F-TEST MAP, AND SCALE WITH THE SCALEFACTOR.           */

    read_float_data(argv[1], stats_map, num_vox);

    for (vox_index=0; vox_index<num_vox; vox_index++)
        stats_map[vox_index]*=scalefactor;

    printf("F2Z: converting F-tests to Z-scores...\n");


/* ---------------------------------------------------------------------------- */
/* IF NUMERATOR DEGREES OF FREEDOM IS NOT 1, USE PAULSON TO CONVERT F-TESTS TO  */
/* Z-SCORES.                                                                    */

    if (v1!=1) {
	printf("Using Paulson's method...\n");
        for (vox_index=0; vox_index<num_vox; vox_index++)
            Z_score_map[vox_index]=
                    ((1.-2./(9.*(double)v2))*
                pow((double)stats_map[vox_index],1./3.) - (1.-2./(9.*(double)v1)))
                                            /
                    sqrt((pow((double)stats_map[vox_index],2./3.)*2./
                        (9.*(double)v2)) + (2./(9.*(double)v1)));
    }


/* ---------------------------------------------------------------------------- */
/* IF NUMERATOR DEGREES OF FREEDOM IS EQUAL TO 1, USE FEDERIGHI TO CONVERT      */
/* F-TESTS TO Z-SCORES.                                                         */

    else {
        /* -------------------------------------------------------------------- */
        /* TAKE SQUARE ROOT TO CONVERT F-TESTS INTO T-TESTS.  Just in case      */
        /* we're dealing with "signed" F-tests, we take the absolute value of   */
        /* the F-test. We use the "fabs" function, not the "abs" function.      */
        /* Right, Jack?                                                         */

        for (vox_index=0; vox_index<num_vox; vox_index++)
            stats_map[vox_index]=(float)sqrt(fabs((double)stats_map[vox_index]));


        /* -------------------------------------------------------------------- */
        /* APPLY FEDERIGHI TO T-TESTS.                                          */

	printf("Using Federighi's method...\n");
        for (vox_index=0; vox_index<num_vox; vox_index++)
            Z_score_map[vox_index]=
                        sqrt((double)v2*log(1.+(double)stats_map[vox_index]*
                                (double)stats_map[vox_index]/(double)v2)
                                                * (1.-(1./(2.*(double)v2))));


        /* ---------------------------------------------------------------------*/
        /* IF A SIGN MAP WAS GIVEN AT THE COMMAND LINE, READ IT IN, AND THEN    */
        /* GIVE NEGATIVE SIGN TO Z-SCORES WHERE SIGN MAP IS NEGATIVE.           */

        if (argc==7) {
            sign_map = (float *) malloc(num_vox*sizeof(float));
            read_float_data(argv[6], sign_map, num_vox);

            for (vox_index=0; vox_index<num_vox; vox_index++)
                if (sign_map[vox_index]<0.)
                    Z_score_map[vox_index]*=-1.;

            free(sign_map);
        }
    }


/* ---------------------------------------------------------------------------- */
/* WRITE Z-SCORE MAP TO OUTPUT FILE.                                            */

    float_fwrite(argv[5], Z_score_map, num_vox);

    free(stats_map);
    free(Z_score_map);
}
